name: Tests

on:
  push:
  pull_request:

jobs:
  pytest:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 181818
          POSTGRES_DB: gradcafe_db_v2
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    defaults:
      run:
        working-directory: Module_4

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.14"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r src/requirements.txt
          python -m pip install pytest pytest-cov psycopg-binary

      - name: Create applicants table
        run: |
          PGPASSWORD=181818 psql -h localhost -U postgres -d gradcafe_db_v2 -c "
          CREATE TABLE IF NOT EXISTS applicants (
              p_id SERIAL PRIMARY KEY,
              program TEXT,
              comments TEXT,
              date_added date,
              url TEXT,
              status TEXT,
              term TEXT,
              us_or_international TEXT,
              gpa FLOAT,
              gre FLOAT,
              gre_v FLOAT,
              gre_aw FLOAT,
              degree TEXT,
              llm_generated_program TEXT,
              llm_generated_university TEXT
          );"

      - name: Run pytest
        run: python -m pytest